---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: run gcc
      command: gcc --version

    - name: run make
      command: make --version

    - name: run shasum
      command: shasum --version

    - name: run bison
      command: bison --version
