---
#
# Ansible managed
#
repository:
  description: Find and update pip packages.
  homepage: https://robertdebock.nl/
  topics: updatepippackages, pip, update, security, ansible, molecule, tox, playbook
