---

- name: get all installed packages
  community.general.pip_package_info:
    clients: "{{ client }}"
  register: update_pip_packages
  environment:
    path: "/bin:/usr/local/bin"

- name: include package.yml
  include: package.yml
  with_dict: "{{ update_pip_packages.packages[client] }}"
  loop_control:
    loop_var: package
    label: "{{ package.key }}"
