---
# tasks file for update_pip_packages

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: include client.yml
  ansible.builtin.include: client.yml
  loop: "{{ update_pip_packages_clients }}"
