---
# tasks file for update_pip_packages

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: get all installed packages
  community.general.pip_package_info:
    clients: "{{ item }}"
  loop: "{{ update_pip_packages_clients }}"
  register: update_pip_packages_installed

- name: show shit
  ansible.builtin.debug:
    msg: "{{ update_pip_packages_installed }}"

- name: include pip.yml
  ansible.builtin.include: packages.yml
  loop: "{{ update_pip_packages_clients }}"
  loop_control:
    loop_var: client
