---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip

  tasks:
    - name: Install pip package (try without flags)
      block:
        - name: Install pip package
          ansible.builtin.pip:
            name: ansible
      rescue:
        - name: Retry install with --break-system-packages when supported
          ansible.builtin.pip:
            name: ansible
            break_system_packages: true
            extra_args: --break-system-packages
