---
galaxy_info:
  author: Robert de Bock
  namespace: robertdebock
  role_name: python_pip
  description: Install pythons pip on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.10

  platforms:
    - name: EL
      versions:
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 32
        - 33
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic

  galaxy_tags:
    - python
    - pip
    - pypip
    - system
    - installer

dependencies: []
